config/routes.rb
Rails.application.routes.draw do
  
  root to: "picture_stores#index"
  resources :picture_stores

end

app/models/picture_store.rb
class PictureStore < ActiveRecord::Base
    mount_uploader :picture, PictureUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/picture_stores_controller.rb
class PictureStoresController < ApplicationController
  before_action :set_picture_store, only: [:show, :edit, :update, :destroy]

  # GET /picture_stores
  # GET /picture_stores.json
  def index
    @picture_stores = PictureStore.all
  end

  # GET /picture_stores/1
  # GET /picture_stores/1.json
  def show
  end

  # GET /picture_stores/new
  def new
    @picture_store = PictureStore.new
  end

  # GET /picture_stores/1/edit
  def edit
  end

  # POST /picture_stores
  # POST /picture_stores.json
  def create
    @picture_store = PictureStore.new(picture_store_params)

    respond_to do |format|
      if @picture_store.save
        format.html { redirect_to @picture_store, notice: 'Picture store was successfully created.' }
        format.json { render :show, status: :created, location: @picture_store }
      else
        format.html { render :new }
        format.json { render json: @picture_store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /picture_stores/1
  # PATCH/PUT /picture_stores/1.json
  def update
    respond_to do |format|
      if @picture_store.update(picture_store_params)
        format.html { redirect_to @picture_store, notice: 'Picture store was successfully updated.' }
        format.json { render :show, status: :ok, location: @picture_store }
      else
        format.html { render :edit }
        format.json { render json: @picture_store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /picture_stores/1
  # DELETE /picture_stores/1.json
  def destroy
    @picture_store.destroy
    respond_to do |format|
      format.html { redirect_to picture_stores_url, notice: 'Picture store was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture_store
      @picture_store = PictureStore.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_store_params
      params.require(:picture_store).permit(:store_name, :picture)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/picture_stores_helper.rb
module PictureStoresHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pictureup</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/picture_stores/_form.html.erb
<%= form_for(@picture_store) do |f| %>
  <% if @picture_store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@picture_store.errors.count, "error") %> prohibited this picture_store from being saved:</h2>

      <ul>
      <% @picture_store.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :store_name %><br>
    <%= f.text_field :store_name %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
    <%= f.hidden_field :picture_cache %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/picture_stores/edit.html.erb
<h1>Editing Picture Store</h1>

<%= render 'form' %>

<%= link_to 'Show', @picture_store %> |
<%= link_to 'Back', picture_stores_path %>

app/views/picture_stores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Picture Stores</h1>

<table>
  <thead>
    <tr>
      <th>Store name</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @picture_stores.each do |picture_store| %>
      <tr>
        <td><%= picture_store.store_name %></td>
        <td><%= picture_store.picture %></td>
        <td><%= link_to 'Show', picture_store %></td>
        <td><%= link_to 'Edit', edit_picture_store_path(picture_store) %></td>
        <td><%= link_to 'Destroy', picture_store, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Picture store', new_picture_store_path %>

app/views/picture_stores/new.html.erb
<h1>New Picture Store</h1>

<%= render 'form' %>

<%= link_to 'Back', picture_stores_path %>

app/views/picture_stores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Store name:</strong>
  <%= @picture_store.store_name %>
</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag @picture_store.picture.url %>
</p>

<%= link_to 'Edit', edit_picture_store_path(@picture_store) %> |
<%= link_to 'Back', picture_stores_path %>